// Generated by https://quicktype.io

import { Empresa } from "./empresa";

export interface Factura {
    id:             number;
    identificacion: string;
    subTotal:       number;
    total:          number;
    fecha:          string;
    codigo:         string;
    empresa:        Empresa;
}

 
